INSERT INTO TABLE_USER (FIRST_NAME, LAST_NAME, LOGIN_NAME, PASS, IS_BLOQUED, LAST_LOGIN, LAST_BAD_LOGIN, BAD_LOGIN_COUNT) VALUES ('Admin','User', 'Asmsa1', 'Asmsa1', 0, NULL, NULL, 0);

INSERT INTO TABLE_ROLE (TITLE, IS_ACTIVE) VALUES ('ADMIN', 1);

INSERT INTO TABLE_USER_X_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);

INSERT INTO TABLE_CONTACT (FIRST_NAME, LAST_NAME, OTHER_NAME, PHONE, EMAIL, ADDRESS_ID, BIRTHDATE, GENDER, TAX_REGIME, DOCUMENT_TYPE, DOCUMENT_NUMBER, LAST_UPDATE) VALUES ('EMMANUEL', 'SALCIDO', 'EL COMPA', '1234567890', 'beco@hotmail.com', 1, TO_DATE('12-07-1989','DD-MM-YYYY'), 1, 1, 1, '12345', TO_DATE('26-05-2019','DD-MM-YYYY'));

INSERT INTO TABLE_ADDRESS (STREET, EXT_NUM, INT_NUM, NEIGHBORHOOD, CITY_ID, STATE_ID, ZIPCODE) VALUES ('UXMAL', '256', NULL, 'MONUMENTAL', 0, 0,'44320');

INSERT INTO TABLE_GENDER (GENDER_NAME) VALUES ('MALE');
INSERT INTO TABLE_GENDER (GENDER_NAME) VALUES ('FEMALE');

INSERT INTO TABLE_TAX_REG (TAX_NAME) VALUES ('PERSONA FISICA');
INSERT INTO TABLE_TAX_REG (TAX_NAME) VALUES ('PERSONA MORAL');

INSERT INTO TABLE_CONTACT_IDENT (DOCUMENT_NAME) VALUES ('INE');
INSERT INTO TABLE_CONTACT_IDENT (DOCUMENT_NAME) VALUES ('PASSPORT');