CREATE TABLE TABLE_USER (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(30) NOT NULL,
    PASS VARCHAR(100) NOT NULL
);

CREATE TABLE TABLE_AUTHORITY(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL
);

CREATE TABLE USER_AUTHORITY(
    USER_ID BIGINT,
    AUTHORITY_ID BIGINT
);

CREATE TABLE TABLE_CONTACT(
    CONTACT_ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    OTHER_NAME VARCHAR(30),
    PHONE VARCHAR(30),
    EMAIL VARCHAR(30),
    ADDRESS_ID BIGINT,
    BIRTHDATE DATE NOT NULL,
    GENDER INT,
    TAX_REGIME INT NOT NULL,
    DOCUMENT_TYPE INT,
    DOCUMENT_NUMBER VARCHAR(30),
    LAST_UPDATE DATE
);

CREATE TABLE TABLE_ADDRESS(
    ADDRESS_ID SERIAL PRIMARY KEY,
    STREET VARCHAR(50) NOT NULL,
    EXT_NUM VARCHAR(20) NOT NULL,
    INT_NUM VARCHAR(20),
    NEIGHBORHOOD VARCHAR(30),
    CITY_ID BIGINT NOT NULL,
    STATE_ID BIGINT NOT NULL,
    ZIPCODE VARCHAR(10)
);

CREATE TABLE TABLE_GENDER(
    GENDER_ID SERIAL PRIMARY KEY,
    GENDER_NAME VARCHAR(20) NOT NULL
);

CREATE TABLE TABLE_TAX_REG(
    TAX_ID SERIAL PRIMARY KEY,
    TAX_NAME VARCHAR(20) NOT NULL
);

CREATE TABLE TABLE_CONTACT_IDENT(
    DOCUMENT_ID SERIAL PRIMARY KEY,
    DOCUMENT_NAME VARCHAR(20) NOT NULL
);

CREATE TABLE TABLE_CITY(
    CITY_ID SERIAL PRIMARY KEY,
    CITY_NAME VARCHAR(30) NOT NULL
);

CREATE TABLE TABLE_STATE(
    STATE_ID SERIAL PRIMARY KEY,
    STATE_NAME VARCHAR(30) NOT NULL
);

INSERT INTO TABLE_USER (USERNAME, PASS) VALUES ('sa','f9fb5cf66c27be875a452c6d2de7978bf4465eed0f1520b897f76e1970bfcda652255e2a2bda9e87');

INSERT INTO TABLE_AUTHORITY (NAME) VALUES ('ROLE_USER');
INSERT INTO TABLE_AUTHORITY (NAME) VALUES ('ROLE_ADMIN');


INSERT INTO TABLE_CONTACT (FIRST_NAME, LAST_NAME, OTHER_NAME, PHONE, EMAIL, ADDRESS_ID, BIRTHDATE, GENDER, TAX_REGIME, DOCUMENT_TYPE, DOCUMENT_NUMBER, LAST_UPDATE) VALUES ('EMMANUEL', 'SALCIDO', 'EL COMPA', '3314261518', 'beco@hotmail.com', 1, TO_DATE('12-07-1989','DD-MM-YYYY'), 1, 1, 2, '12345', TO_DATE('26-05-2019','DD-MM-YYYY'));

INSERT INTO TABLE_CONTACT (FIRST_NAME, LAST_NAME, OTHER_NAME, PHONE, EMAIL, ADDRESS_ID, BIRTHDATE, GENDER, TAX_REGIME, DOCUMENT_TYPE, DOCUMENT_NUMBER, LAST_UPDATE) VALUES ('ANA YATZIKURI', 'TORRES', 'Amorcito', '3319953558', 'yatzikuri@hotmail.com', 3, TO_DATE('07-05-1991','DD-MM-YYYY'), 2, 1, 2, '12345', TO_DATE('26-05-2019','DD-MM-YYYY'));

INSERT INTO TABLE_CONTACT (FIRST_NAME, LAST_NAME, OTHER_NAME, PHONE, EMAIL, ADDRESS_ID, BIRTHDATE, GENDER, TAX_REGIME, DOCUMENT_TYPE, DOCUMENT_NUMBER, LAST_UPDATE) VALUES ('PAVEL', 'ANGULO', 'PASHA', '3318152614', 'pasha@hotmail.com', 2, TO_DATE('10-07-1989','DD-MM-YYYY'), 1, 2, 2, '12345', TO_DATE('26-05-2019','DD-MM-YYYY'));

INSERT INTO TABLE_CONTACT (FIRST_NAME, LAST_NAME, OTHER_NAME, PHONE, EMAIL, ADDRESS_ID, BIRTHDATE, GENDER, TAX_REGIME, DOCUMENT_TYPE, DOCUMENT_NUMBER, LAST_UPDATE) VALUES ('EMMANUEL', 'CUEVAZ', null, '3311223344', 'beco@hotmail.com', 1, TO_DATE('12-07-1989','DD-MM-YYYY'), 1, 1, 2, '12345', TO_DATE('26-05-2019','DD-MM-YYYY'));

INSERT INTO TABLE_ADDRESS (STREET, EXT_NUM, INT_NUM, NEIGHBORHOOD, CITY_ID, STATE_ID, ZIPCODE) VALUES ('UXMAL', '256', NULL, 'MONUMENTAL', 1, 1,'44320');
INSERT INTO TABLE_ADDRESS (STREET, EXT_NUM, INT_NUM, NEIGHBORHOOD, CITY_ID, STATE_ID, ZIPCODE) VALUES ('UXMAL', '1142', NULL, 'MONUMENTAL', 1, 1,'44320');INSERT INTO TABLE_ADDRESS (STREET, EXT_NUM, INT_NUM, NEIGHBORHOOD, CITY_ID, STATE_ID, ZIPCODE) VALUES ('Antiguo Camino a Copalita', '2711', NULL, 'Valle Imperial', 1, 1,'44320');

INSERT INTO TABLE_GENDER (GENDER_NAME) VALUES ('MALE');
INSERT INTO TABLE_GENDER (GENDER_NAME) VALUES ('FEMALE');

INSERT INTO TABLE_TAX_REG (TAX_NAME) VALUES ('PERSONA FISICA');
INSERT INTO TABLE_TAX_REG (TAX_NAME) VALUES ('PERSONA MORAL');

INSERT INTO TABLE_CONTACT_IDENT (DOCUMENT_NAME) VALUES ('INE');
INSERT INTO TABLE_CONTACT_IDENT (DOCUMENT_NAME) VALUES ('PASSPORT');

INSERT INTO TABLE_CITY (CITY_NAME) VALUES ('GUADALAJARA');

INSERT INTO TABLE_STATE (STATE_NAME) VALUES ('JALISCO');