version: "3"
services:

  postgres:
    image: postgres
    network_mode: bridge
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose: 
      - 5432
    ports:
      - 5432:5432
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=demo_db
    restart: unless-stopped

  arkhe-app:
    image: arkhe-app
    network_mode: bridge
    container_name: arkhe-app
    expose:
      - 8080
    ports: 
      - 8080:8080
    # restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    
volumes:
  postgres-data: